"""Self-contained HTML preview of detected spans."""

from __future__ import annotations

from html import escape


_LABEL_COLORS = {
    "KISI_ADI":       ("#fde68a", "#78350f"),
    "TCKN":           ("#fecaca", "#7f1d1d"),
    "VKN":            ("#fbcfe8", "#831843"),
    "TELEFON":        ("#bfdbfe", "#1e3a8a"),
    "EPOSTA":         ("#bae6fd", "#075985"),
    "ADRES":          ("#c7d2fe", "#312e81"),
    "TARIH":          ("#d9f99d", "#365314"),
    "POLICE_NO":      ("#fed7aa", "#7c2d12"),
    "HASAR_DOSYA_NO": ("#fcd34d", "#78350f"),
    "PLAKA":          ("#a7f3d0", "#064e3b"),
    "SASI_NO":        ("#99f6e4", "#134e4a"),
    "IBAN":           ("#f5d0fe", "#581c87"),
    "SGK_NO":         ("#fda4af", "#881337"),
}

_DEFAULT_COLORS = ("#e5e7eb", "#374151")


def _chip(text: str, label: str) -> str:
    bg, fg = _LABEL_COLORS.get(label, _DEFAULT_COLORS)
    return (
        f'<span class="pii-chip" style="background:{bg};color:{fg};">'
        f'{escape(text)}'
        f'<span class="pii-tag">{label}</span>'
        f'</span>'
    )


def render_inline(text: str, spans: list[dict]) -> str:
    out: list[str] = []
    cursor = 0
    for span in sorted(spans, key=lambda s: s["start"]):
        out.append(escape(text[cursor:span["start"]]))
        out.append(_chip(text[span["start"]:span["end"]], span["label"]))
        cursor = span["end"]
    out.append(escape(text[cursor:]))
    return "".join(out)


def render_legend(spans: list[dict]) -> str:
    seen: dict[str, int] = {}
    for span in spans:
        seen[span["label"]] = seen.get(span["label"], 0) + 1
    chips = []
    for label, count in sorted(seen.items()):
        bg, fg = _LABEL_COLORS.get(label, _DEFAULT_COLORS)
        chips.append(
            f'<span class="legend-chip" style="background:{bg};color:{fg};">'
            f'{label} <span class="legend-count">{count}</span>'
            f'</span>'
        )
    return "".join(chips)


def render_preview_html(text: str, spans: list[dict], *, source: str) -> str:
    legend = render_legend(spans)
    body = render_inline(text, spans) if text else "<em>empty document</em>"
    total = len(spans)
    return f"""<!doctype html>
<html lang="tr">
<head>
<meta charset="utf-8">
<title>{escape(source)} — pii-mask-tr</title>
<style>
  :root {{
    --bg: #0f1115;
    --panel: #1a1d24;
    --text: #e7e9ee;
    --muted: #8a8f98;
    --border: #2a2e37;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0;
    background: var(--bg);
    color: var(--text);
    font: 14px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  }}
  header {{
    padding: 24px 32px 16px;
    border-bottom: 1px solid var(--border);
  }}
  h1 {{
    font-size: 15px;
    font-weight: 500;
    margin: 0 0 4px 0;
    color: var(--muted);
    letter-spacing: 0.02em;
  }}
  .source {{
    font: 13px ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
    color: var(--text);
  }}
  .summary {{
    margin-top: 12px;
    color: var(--muted);
    font-size: 13px;
  }}
  .summary strong {{ color: var(--text); }}
  .legend {{
    padding: 16px 32px;
    border-bottom: 1px solid var(--border);
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }}
  .legend-chip {{
    padding: 4px 10px;
    border-radius: 12px;
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 0.02em;
  }}
  .legend-count {{
    margin-left: 4px;
    opacity: 0.7;
    font-weight: 400;
  }}
  main {{
    padding: 32px;
    max-width: 980px;
    margin: 0 auto;
  }}
  pre.doc {{
    white-space: pre-wrap;
    word-wrap: break-word;
    font: 14px/1.7 ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
    margin: 0;
    padding: 24px;
    background: var(--panel);
    border: 1px solid var(--border);
    border-radius: 6px;
  }}
  .pii-chip {{
    padding: 1px 6px 1px 6px;
    border-radius: 4px;
    font-weight: 500;
    position: relative;
  }}
  .pii-tag {{
    display: inline-block;
    margin-left: 5px;
    font-size: 9px;
    font-weight: 700;
    letter-spacing: 0.05em;
    opacity: 0.65;
    vertical-align: 1px;
  }}
  footer {{
    padding: 24px 32px;
    color: var(--muted);
    font-size: 12px;
    text-align: center;
  }}
</style>
</head>
<body>
<header>
  <h1>pii-mask-tr · detection preview</h1>
  <div class="source">{escape(source)}</div>
  <div class="summary"><strong>{total}</strong> entities detected across {len(set(s["label"] for s in spans))} classes</div>
</header>
<div class="legend">{legend}</div>
<main><pre class="doc">{body}</pre></main>
<footer>Generated by pii-mask-tr · model: BERTurk + CRF</footer>
</body>
</html>
"""
